In [81]:
import numpy as np
import pandas as pd
import seaborn as sns

In [82]:
data = pd.read_csv(r"M:\DATA ANALYST\INTERNSHIP ASSIGNMENT 1\Nassau Candy Distributor.csv")      # Reading CSV file

In [83]:
data.head()           # Checking Data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

1. Row ID - Unique Row Identifier
2. Order ID - Unique Order Identifier
3. Order Date - Date of order
4. Ship Date - Date of shipment
5. Ship Mode - Shipping method of order
6. Customer ID	 - Unique customer identifier
7. Country/Region - Country or region of customer
8. City - City of customer
9. State/Province - State/province of customer
10. Postal Code - Postal code / zip code of customer
11. Division - Product division
12. Region - Region of customer
13. Product ID - Unique product identifier
14. Product Name - Product long namer
15. Sales - Total sales value of order
16. Units -	Total units of order
17. Gross Profit - Gross profit of order ( Sales - Cost )
18. Cost -	Cost to manufacture

In [84]:
data.info()         # 10194 rows, 18 columns.

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB

In [85]:
data = data[(data['Sales']>=0) & (data['Units']>=0) & (data['Cost']>=0) & (data['Gross Profit']>=0)]                   # Checking Sales, Units and Cost are Valid.

In [86]:
data.shape                        # All data is valid as 10194 rows and 18 columns.

(10194, 18)

We do not need to remove any row as the data is valid.

# CREATING KPI's Groupby Products

In [91]:
data['Product Name'].unique()             # There are 15 unique products.

<StringArray>
[       'Wonka Bar - Milk Chocolate', 'Wonka Bar - Triple Dazzle Caramel',
 'Wonka Bar - Nutty Crunch Surprise',    'Wonka Bar -Scrumdiddlyumptious',
         'Wonka Bar - Fudge Mallows',                         'Wonka Gum',
                         'Kazookles',                'Lickable Wallpaper',
              'Fizzy Lifting Drinks',                       'Laffy Taffy',
                         'SweeTARTS',                             'Nerds',
                       'Hair Toffee',            'Everlasting Gobstopper',
                           'Fun Dip']
Length: 15, dtype: str

In [134]:
new_data = data.groupby('Product Name').agg({'Cost':'sum','Sales':'sum','Units':'sum','Gross Profit':'sum'}).reset_index()
# creating a new database which contains parameters according to product name.

In [135]:
new_data.head(15)

                         Product Name     Cost     Sales  Units  Gross Profit
0              Everlasting Gobstopper    26.00    130.00     13        104.00
1                Fizzy Lifting Drinks    31.50     78.75     21         47.25
2                             Fun Dip     7.20     12.00      8          4.80
3                         Hair Toffee    17.00     76.50     17         59.50
4                           Kazookles  1113.00   1205.75    371         92.75
5                         Laffy Taffy    20.25     53.73     27         33.48
6                  Lickable Wallpaper  3930.00   7860.00    393       3930.00
7                               Nerds     8.00     15.00     10          7.00
8                           SweeTARTS    32.80     61.50     41         28.70
9           Wonka Bar - Fudge Mallows  8296.80  24890.40   6914      16593.60
10         Wonka Bar - Milk Chocolate  9424.38  26867.75   8267      17443.37
11  Wonka Bar - Nutty Crunch Surprise  6755.00  23574.95   6755      16819.95
12  Wonka Bar - Triple Dazzle Caramel  9874.80  28485.00   7596      18610.20
13     Wonka Bar -Scrumdiddlyumptious  8517.30  27874.80   7743      19357.50
14                          Wonka Gum   286.80    597.50    478        310.70

Gross Margin % = Gross Profit/Sales

In [136]:
new_data['Gross Margin %'] = ((new_data['Gross Profit']/new_data['Sales'])*100).round(2)  # creating new column

In [137]:
new_data.head(15)

,Product Name,Cost,Sales,Units,Gross Profit,Gross Margin %
0,Everlasting Gobstopper,26.00,130.00,13,104.00,80.00
1,Fizzy Lifting Drinks,31.50,78.75,21,47.25,60.00
2,Fun Dip,7.20,12.00,8,4.80,40.00
3,Hair Toffee,17.00,76.50,17,59.50,77.78
4,Kazookles,1113.00,1205.75,371,92.75,7.69
5,Laffy Taffy,20.25,53.73,27,33.48,62.31
6,Lickable Wallpaper,3930.00,7860.00,393,3930.00,50.00
7,Nerds,8.00,15.00,10,7.00,46.67
8,SweeTARTS,32.80,61.50,41,28.70,46.67
9,Wonka Bar - Fudge Mallows,8296.80,24890.40,6914,16593.60,66.67
10,Wonka Bar - Milk Chocolate,9424.38,26867.75,8267,17443.37,64.92
11,Wonka Bar - Nutty Crunch Surprise,6755.00,23574.95,6755,16819.95,71.35
12,Wonka Bar - Triple Dazzle Caramel,9874.80,28485.00,7596,18610.20,65.33
13,Wonka Bar -Scrumdiddlyumptious,8517.30,27874.80,7743,19357.50,69.44
14,Wonka Gum,286.80,597.50,478,310.70,52.00

Profit Per Unit = Gross Profit/ Units

In [138]:
new_data['Profit Per Unit'] = (new_data['Gross Profit']/new_data['Units']).round(2)  # creating new column

In [139]:
new_data.head(15)

,Product Name,Cost,Sales,Units,Gross Profit,Gross Margin %,Profit Per Unit
0,Everlasting Gobstopper,26.00,130.00,13,104.00,80.00,8.00
1,Fizzy Lifting Drinks,31.50,78.75,21,47.25,60.00,2.25
2,Fun Dip,7.20,12.00,8,4.80,40.00,0.60
3,Hair Toffee,17.00,76.50,17,59.50,77.78,3.50
4,Kazookles,1113.00,1205.75,371,92.75,7.69,0.25
5,Laffy Taffy,20.25,53.73,27,33.48,62.31,1.24
6,Lickable Wallpaper,3930.00,7860.00,393,3930.00,50.00,10.00
7,Nerds,8.00,15.00,10,7.00,46.67,0.70
8,SweeTARTS,32.80,61.50,41,28.70,46.67,0.70
9,Wonka Bar - Fudge Mallows,8296.80,24890.40,6914,16593.60,66.67,2.40
10,Wonka Bar - Milk Chocolate,9424.38,26867.75,8267,17443.37,64.92,2.11
11,Wonka Bar - Nutty Crunch Surprise,6755.00,23574.95,6755,16819.95,71.35,2.49
12,Wonka Bar - Triple Dazzle Caramel,9874.80,28485.00,7596,18610.20,65.33,2.45
13,Wonka Bar -Scrumdiddlyumptious,8517.30,27874.80,7743,19357.50,69.44,2.50
14,Wonka Gum,286.80,597.50,478,310.70,52.00,0.65

Revenue Contribution = Product Sales/ Total Sales

In [140]:
Total_Sales = new_data['Sales'].sum()
print(Total_Sales)

141783.63

In [141]:
new_data['Revenue Contribution'] = ((new_data['Sales']/Total_Sales)*100).round(2)     # creating new column

In [142]:
new_data.head(15)

,Product Name,Cost,Sales,Units,Gross Profit,Gross Margin %,Profit Per Unit,Revenue Contribution
0,Everlasting Gobstopper,26.00,130.00,13,104.00,80.00,8.00,0.09
1,Fizzy Lifting Drinks,31.50,78.75,21,47.25,60.00,2.25,0.06
2,Fun Dip,7.20,12.00,8,4.80,40.00,0.60,0.01
3,Hair Toffee,17.00,76.50,17,59.50,77.78,3.50,0.05
4,Kazookles,1113.00,1205.75,371,92.75,7.69,0.25,0.85
5,Laffy Taffy,20.25,53.73,27,33.48,62.31,1.24,0.04
6,Lickable Wallpaper,3930.00,7860.00,393,3930.00,50.00,10.00,5.54
7,Nerds,8.00,15.00,10,7.00,46.67,0.70,0.01
8,SweeTARTS,32.80,61.50,41,28.70,46.67,0.70,0.04
9,Wonka Bar - Fudge Mallows,8296.80,24890.40,6914,16593.60,66.67,2.40,17.56
10,Wonka Bar - Milk Chocolate,9424.38,26867.75,8267,17443.37,64.92,2.11,18.95
11,Wonka Bar - Nutty Crunch Surprise,6755.00,23574.95,6755,16819.95,71.35,2.49,16.63
12,Wonka Bar - Triple Dazzle Caramel,9874.80,28485.00,7596,18610.20,65.33,2.45,20.09
13,Wonka Bar -Scrumdiddlyumptious,8517.30,27874.80,7743,19357.50,69.44,2.50,19.66
14,Wonka Gum,286.80,597.50,478,310.70,52.00,0.65,0.42

Profit Contribution = Product Profit/Total Profit

In [143]:
new_data['Profit contribution'] = ((new_data['Gross Profit']/(new_data['Gross Profit'].sum()))*100).round(2) # creating new column

In [144]:
new_data.head(15)

,Product Name,Cost,Sales,Units,Gross Profit,Gross Margin %,Profit Per Unit,Revenue Contribution,Profit contribution
0,Everlasting Gobstopper,26.00,130.00,13,104.00,80.00,8.00,0.09,0.11
1,Fizzy Lifting Drinks,31.50,78.75,21,47.25,60.00,2.25,0.06,0.05
2,Fun Dip,7.20,12.00,8,4.80,40.00,0.60,0.01,0.01
3,Hair Toffee,17.00,76.50,17,59.50,77.78,3.50,0.05,0.06
4,Kazookles,1113.00,1205.75,371,92.75,7.69,0.25,0.85,0.10
5,Laffy Taffy,20.25,53.73,27,33.48,62.31,1.24,0.04,0.04
6,Lickable Wallpaper,3930.00,7860.00,393,3930.00,50.00,10.00,5.54,4.21
7,Nerds,8.00,15.00,10,7.00,46.67,0.70,0.01,0.01
8,SweeTARTS,32.80,61.50,41,28.70,46.67,0.70,0.04,0.03
9,Wonka Bar - Fudge Mallows,8296.80,24890.40,6914,16593.60,66.67,2.40,17.56,17.76
10,Wonka Bar - Milk Chocolate,9424.38,26867.75,8267,17443.37,64.92,2.11,18.95,18.67
11,Wonka Bar - Nutty Crunch Surprise,6755.00,23574.95,6755,16819.95,71.35,2.49,16.63,18.00
12,Wonka Bar - Triple Dazzle Caramel,9874.80,28485.00,7596,18610.20,65.33,2.45,20.09,19.92
13,Wonka Bar -Scrumdiddlyumptious,8517.30,27874.80,7743,19357.50,69.44,2.50,19.66,20.72
14,Wonka Gum,286.80,597.50,478,310.70,52.00,0.65,0.42,0.33

# CREATING KPI's Groupby DIVISION

In [145]:
data.head(1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Gross Margin %,Profit Per Unit
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.5,2,4.22,2.28,64.92,2.11

In [146]:
data['Division'].unique()       # Three types of Division : Chocolate, Sugar and Other

<StringArray>
['Chocolate', 'Other', 'Sugar']
Length: 3, dtype: str

In [147]:
division_data = data.groupby('Division').agg({'Cost':'sum','Sales':'sum','Units':'sum','Gross Profit':'sum'}).reset_index()

In [148]:
division_data.head()

    Division      Cost      Sales  Units  Gross Profit
0  Chocolate  42868.28  131692.90  37275      88824.62
1      Other   5329.80    9663.25   1242       4333.45
2      Sugar    142.75     427.48    137        284.73

In [ ]:
division_data['Gross Margin %'] = ((division_data['Gross Profit']/division_data['Sales'])*100).round(2) # adding gross margin %

In [ ]:
division_data['Profit Per Unit'] = ((division_data['Gross Profit']/division_data['Units'])*100).round(2) # adding profit per unit

In [151]:
division_data['Revenue Contribution'] = (division_data['Sales']/(division_data['Sales'].sum())*100).round(2) # adding revenue contribution

In [152]:
division_data['Profit contribution'] = (division_data['Gross Profit']/(division_data['Gross Profit'].sum())*100).round(2) # adding profit contribution

In [153]:
division_data.head()

,Division,Cost,Sales,Units,Gross Profit,Gross Margin %,Profit Per Unit,Revenue Contribution,Profit contribution
0,Chocolate,42868.28,131692.90,37275,88824.62,67.45,238.30,92.88,95.06
1,Other,5329.80,9663.25,1242,4333.45,44.84,348.91,6.82,4.64
2,Sugar,142.75,427.48,137,284.73,66.61,207.83,0.30,0.30